import random

bd = {
    "Neymar": ["A Footballer, from Brazil", 1000],
    "Cristiano Ronaldo": ["A Footballer, from Portugal", 5234],
    "Lionel Messi": ["A Footballer, from Argentina", 8472],
    "Kylian Mbappe": ["A Footballer, from France", 3921],
    "Shakira": ["A Singer, from Colombia", 7643],
    "Taylor Swift": ["A Singer, from the USA", 9812],
    "Ariana Grande": ["A Singer, from the USA", 4567],
    "Juanes": ["A Singer, from Colombia", 2345],
    "Billie Eilish": ["A Singer, from the USA", 6789],
    "Ed Sheeran": ["A Singer, from the UK", 3456],
    "Rihanna": ["A Singer, from Barbados", 7890],
    "Drake": ["A Rapper, from Canada", 1234],
    "Illia Topuria": ["A Fighter, from Spain", 5678],
    "Conor McGregor": ["A Fighter, from Ireland", 4321],
    "Khabib Nurmagomedov": ["A Fighter, from Russia", 8765],
    "Max Holloway": ["A Fighter, from the USA", 2341],
    "Michael Jordan": ["A Basketball Player, from the USA", 6543],
    "LeBron James": ["A Basketball Player, from the USA", 9876],
    "Ibai Llanos": ["A Streamer, from Spain", 3452],
    "Ninja": ["A Streamer, from the USA", 6781],
    "Pokimane": ["A Streamer, from Morocco", 1235],
    "Rubius": ["A Streamer, from Spain", 4568],
    "AuronPlay": ["A Streamer, from Spain", 7891],
    "ElRubius": ["A Streamer, from Spain", 2346],
    "Dani Alves": ["A Footballer, from Brazil", 5679],
    "Gerard Piqué": ["A Footballer, from Spain", 4322],
    "Sergio Ramos": ["A Footballer, from Spain", 8766],
}